//! Conformance against the FROZEN shared test vectors.
//!
//! `tests/vectors.json` is a copy of `app/src/lib/envelope/test-vectors.json`
//! in the diff monorepo, generated by the TypeScript implementation. The two
//! copies must stay identical. Passing this suite proves TS-encrypt ->
//! Rust-decrypt compatibility and deterministic-encrypt byte equality.

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use getdiff_envelope::{
    Envelope, EnvelopeError, KeyHolder, Recipient, WrapMaterial, open, seal_with_material,
    unwrap_dek,
};
use serde::Deserialize;

fn unb64(s: &str) -> Vec<u8> {
    URL_SAFE_NO_PAD.decode(s).expect("vector base64url")
}

#[derive(Deserialize)]
struct Vectors {
    suite: String,
    deterministic_encrypt: Vec<DetCase>,
    decrypt: Vec<DecryptCase>,
}

#[derive(Deserialize)]
struct DetCase {
    name: String,
    plaintext: String,
    dek: String,
    #[serde(rename = "valueNonce")]
    value_nonce: String,
    recipients: Vec<VectorRecipient>,
    #[serde(rename = "wrapMaterial")]
    wrap_material: Vec<VectorWrapMaterial>,
    expect: DetExpect,
}

#[derive(Deserialize)]
struct VectorRecipient {
    kid: String,
    role: String,
    #[serde(rename = "publicKeySec1")]
    public_key_sec1: String,
}

#[derive(Deserialize)]
struct VectorWrapMaterial {
    #[serde(rename = "ephemeralScalar")]
    ephemeral_scalar: String,
    nonce: String,
}

#[derive(Deserialize)]
struct DetExpect {
    ct: String,
    wraps: Vec<DetExpectWrap>,
}

#[derive(Deserialize)]
struct DetExpectWrap {
    epk: String,
    wdek: String,
}

#[derive(Deserialize)]
struct DecryptCase {
    name: String,
    envelope: serde_json::Value,
    recipient: VectorHolder,
    expect: DecryptExpect,
}

#[derive(Deserialize)]
struct VectorHolder {
    kid: String,
    #[serde(rename = "privateScalar")]
    private_scalar: String,
}

#[derive(Deserialize)]
struct DecryptExpect {
    plaintext: Option<String>,
    dek: Option<String>,
    error: Option<String>,
}

fn load() -> Vectors {
    let raw = include_str!("vectors.json");
    serde_json::from_str(raw).expect("vectors.json parses")
}

#[test]
fn suite_matches() {
    assert_eq!(load().suite, "ECDH-P256+HKDF-SHA256+A256GCM");
}

#[test]
fn deterministic_encrypt_vectors() {
    for case in load().deterministic_encrypt {
        let recipients: Vec<Recipient> = case
            .recipients
            .iter()
            .map(|r| Recipient {
                kid: r.kid.clone(),
                role: r.role.clone(),
                public_key: unb64(&r.public_key_sec1),
            })
            .collect();
        let per_wrap: Vec<WrapMaterial> = case
            .wrap_material
            .iter()
            .map(|m| WrapMaterial {
                ephemeral_scalar: unb64(&m.ephemeral_scalar),
                nonce: unb64(&m.nonce),
            })
            .collect();
        let dek: [u8; 32] = unb64(&case.dek).try_into().expect("32-byte DEK");
        let envelope = seal_with_material(
            &unb64(&case.plaintext),
            &recipients,
            &dek,
            &unb64(&case.value_nonce),
            Some(&per_wrap),
        )
        .unwrap_or_else(|e| panic!("{}: seal failed: {e}", case.name));

        assert_eq!(envelope.ct, case.expect.ct, "{}: ct mismatch", case.name);
        assert_eq!(
            envelope.wraps.len(),
            case.expect.wraps.len(),
            "{}: wrap count",
            case.name
        );
        for (actual, expected) in envelope.wraps.iter().zip(case.expect.wraps.iter()) {
            assert_eq!(actual.epk, expected.epk, "{}: epk mismatch", case.name);
            assert_eq!(actual.wdek, expected.wdek, "{}: wdek mismatch", case.name);
        }
    }
}

#[test]
fn decrypt_vectors() {
    for case in load().decrypt {
        let envelope: Envelope = serde_json::from_value(case.envelope.clone())
            .expect("envelope parses (unknown fields ignored)");
        let holder = KeyHolder {
            kid: case.recipient.kid.clone(),
            private_scalar: unb64(&case.recipient.private_scalar),
        };
        match case.expect.error.as_deref() {
            Some("tamper") => {
                assert_eq!(
                    open(&envelope, &holder).unwrap_err(),
                    EnvelopeError::Tamper,
                    "{}",
                    case.name
                );
            }
            Some("no_wrap") => {
                assert_eq!(
                    open(&envelope, &holder).unwrap_err(),
                    EnvelopeError::NoWrap,
                    "{}",
                    case.name
                );
            }
            Some(other) => panic!("{}: unknown expected error {other}", case.name),
            None => {
                let plaintext = open(&envelope, &holder)
                    .unwrap_or_else(|e| panic!("{}: open failed: {e}", case.name));
                assert_eq!(
                    URL_SAFE_NO_PAD.encode(&plaintext),
                    case.expect.plaintext.clone().expect("plaintext"),
                    "{}: plaintext mismatch",
                    case.name
                );
                let dek = unwrap_dek(&envelope, &holder).unwrap();
                assert_eq!(
                    URL_SAFE_NO_PAD.encode(dek),
                    case.expect.dek.clone().expect("dek"),
                    "{}: dek mismatch",
                    case.name
                );
            }
        }
    }
}
